// Code generated by protoc-gen-go.
// source: agency/agency.proto
// DO NOT EDIT!

/*
Package agency is a generated protocol buffer package.

It is generated from these files:
	agency/agency.proto
	agency/model.proto

It has these top-level messages:
	Empty
	VersionInfoResponse
	AccountLoginRequest
	AccountLoginResponse
	AccountLogoutRequest
	AccountLogoutResponse
	CustomerLookupRequest
	CustomerLookupResponse
	CustomerActionRequest
	CustomerActionOrder
	CustomerActionResponse
	ReceiveFromSupplierRequest
	ReceiveFromSupplierResponse
	TransferToSupplierRequest
	TransferToSupplierResponse
	AgencyStaff
	Customer
	Order
	OrderInfo
	OrderCustomer
	OrderService
	Service
*/
package agency

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_rpc "google.golang.org/genproto/googleapis/rpc/status"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type VersionInfoResponse struct {
	Service     string `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
	Version     string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	UpdatedTime int64  `protobuf:"varint,3,opt,name=updated_time,json=updatedTime" json:"updated_time,omitempty"`
}

func (m *VersionInfoResponse) Reset()                    { *m = VersionInfoResponse{} }
func (m *VersionInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*VersionInfoResponse) ProtoMessage()               {}
func (*VersionInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *VersionInfoResponse) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *VersionInfoResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *VersionInfoResponse) GetUpdatedTime() int64 {
	if m != nil {
		return m.UpdatedTime
	}
	return 0
}

type AccountLoginRequest struct {
	Phone    string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *AccountLoginRequest) Reset()                    { *m = AccountLoginRequest{} }
func (m *AccountLoginRequest) String() string            { return proto.CompactTextString(m) }
func (*AccountLoginRequest) ProtoMessage()               {}
func (*AccountLoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AccountLoginRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *AccountLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AccountLoginResponse struct {
	UserId      string       `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	AccessToken string       `protobuf:"bytes,2,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	UserInfo    *AgencyStaff `protobuf:"bytes,3,opt,name=user_info,json=userInfo" json:"user_info,omitempty"`
}

func (m *AccountLoginResponse) Reset()                    { *m = AccountLoginResponse{} }
func (m *AccountLoginResponse) String() string            { return proto.CompactTextString(m) }
func (*AccountLoginResponse) ProtoMessage()               {}
func (*AccountLoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AccountLoginResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AccountLoginResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *AccountLoginResponse) GetUserInfo() *AgencyStaff {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type AccountLogoutRequest struct {
}

func (m *AccountLogoutRequest) Reset()                    { *m = AccountLogoutRequest{} }
func (m *AccountLogoutRequest) String() string            { return proto.CompactTextString(m) }
func (*AccountLogoutRequest) ProtoMessage()               {}
func (*AccountLogoutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type AccountLogoutResponse struct {
}

func (m *AccountLogoutResponse) Reset()                    { *m = AccountLogoutResponse{} }
func (m *AccountLogoutResponse) String() string            { return proto.CompactTextString(m) }
func (*AccountLogoutResponse) ProtoMessage()               {}
func (*AccountLogoutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type CustomerLookupRequest struct {
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
}

func (m *CustomerLookupRequest) Reset()                    { *m = CustomerLookupRequest{} }
func (m *CustomerLookupRequest) String() string            { return proto.CompactTextString(m) }
func (*CustomerLookupRequest) ProtoMessage()               {}
func (*CustomerLookupRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CustomerLookupRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type CustomerLookupResponse struct {
	CustomerToken string     `protobuf:"bytes,1,opt,name=customer_token,json=customerToken" json:"customer_token,omitempty"`
	Customer      *Customer  `protobuf:"bytes,2,opt,name=customer" json:"customer,omitempty"`
	Services      []*Service `protobuf:"bytes,3,rep,name=services" json:"services,omitempty"`
	Orders        []*Order   `protobuf:"bytes,4,rep,name=orders" json:"orders,omitempty"`
}

func (m *CustomerLookupResponse) Reset()                    { *m = CustomerLookupResponse{} }
func (m *CustomerLookupResponse) String() string            { return proto.CompactTextString(m) }
func (*CustomerLookupResponse) ProtoMessage()               {}
func (*CustomerLookupResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CustomerLookupResponse) GetCustomerToken() string {
	if m != nil {
		return m.CustomerToken
	}
	return ""
}

func (m *CustomerLookupResponse) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

func (m *CustomerLookupResponse) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *CustomerLookupResponse) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

type CustomerActionRequest struct {
	CustomerToken string                 `protobuf:"bytes,1,opt,name=customer_token,json=customerToken" json:"customer_token,omitempty"`
	CustomerPhone string                 `protobuf:"bytes,2,opt,name=customer_phone,json=customerPhone" json:"customer_phone,omitempty"`
	Orders        []*CustomerActionOrder `protobuf:"bytes,3,rep,name=orders" json:"orders,omitempty"`
}

func (m *CustomerActionRequest) Reset()                    { *m = CustomerActionRequest{} }
func (m *CustomerActionRequest) String() string            { return proto.CompactTextString(m) }
func (*CustomerActionRequest) ProtoMessage()               {}
func (*CustomerActionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CustomerActionRequest) GetCustomerToken() string {
	if m != nil {
		return m.CustomerToken
	}
	return ""
}

func (m *CustomerActionRequest) GetCustomerPhone() string {
	if m != nil {
		return m.CustomerPhone
	}
	return ""
}

func (m *CustomerActionRequest) GetOrders() []*CustomerActionOrder {
	if m != nil {
		return m.Orders
	}
	return nil
}

type CustomerActionOrder struct {
	OrderId   string `protobuf:"bytes,1,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
	ServiceId string `protobuf:"bytes,2,opt,name=service_id,json=serviceId" json:"service_id,omitempty"`
}

func (m *CustomerActionOrder) Reset()                    { *m = CustomerActionOrder{} }
func (m *CustomerActionOrder) String() string            { return proto.CompactTextString(m) }
func (*CustomerActionOrder) ProtoMessage()               {}
func (*CustomerActionOrder) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *CustomerActionOrder) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *CustomerActionOrder) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

type CustomerActionResponse struct {
	OrderSuccess map[string]string             `protobuf:"bytes,1,rep,name=order_success,json=orderSuccess" json:"order_success,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OrderErrors  map[string]*google_rpc.Status `protobuf:"bytes,2,rep,name=order_errors,json=orderErrors" json:"order_errors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *CustomerActionResponse) Reset()                    { *m = CustomerActionResponse{} }
func (m *CustomerActionResponse) String() string            { return proto.CompactTextString(m) }
func (*CustomerActionResponse) ProtoMessage()               {}
func (*CustomerActionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *CustomerActionResponse) GetOrderSuccess() map[string]string {
	if m != nil {
		return m.OrderSuccess
	}
	return nil
}

func (m *CustomerActionResponse) GetOrderErrors() map[string]*google_rpc.Status {
	if m != nil {
		return m.OrderErrors
	}
	return nil
}

type ReceiveFromSupplierRequest struct {
}

func (m *ReceiveFromSupplierRequest) Reset()                    { *m = ReceiveFromSupplierRequest{} }
func (m *ReceiveFromSupplierRequest) String() string            { return proto.CompactTextString(m) }
func (*ReceiveFromSupplierRequest) ProtoMessage()               {}
func (*ReceiveFromSupplierRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type ReceiveFromSupplierResponse struct {
}

func (m *ReceiveFromSupplierResponse) Reset()                    { *m = ReceiveFromSupplierResponse{} }
func (m *ReceiveFromSupplierResponse) String() string            { return proto.CompactTextString(m) }
func (*ReceiveFromSupplierResponse) ProtoMessage()               {}
func (*ReceiveFromSupplierResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type TransferToSupplierRequest struct {
}

func (m *TransferToSupplierRequest) Reset()                    { *m = TransferToSupplierRequest{} }
func (m *TransferToSupplierRequest) String() string            { return proto.CompactTextString(m) }
func (*TransferToSupplierRequest) ProtoMessage()               {}
func (*TransferToSupplierRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type TransferToSupplierResponse struct {
}

func (m *TransferToSupplierResponse) Reset()                    { *m = TransferToSupplierResponse{} }
func (m *TransferToSupplierResponse) String() string            { return proto.CompactTextString(m) }
func (*TransferToSupplierResponse) ProtoMessage()               {}
func (*TransferToSupplierResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func init() {
	proto.RegisterType((*Empty)(nil), "agency.Empty")
	proto.RegisterType((*VersionInfoResponse)(nil), "agency.VersionInfoResponse")
	proto.RegisterType((*AccountLoginRequest)(nil), "agency.AccountLoginRequest")
	proto.RegisterType((*AccountLoginResponse)(nil), "agency.AccountLoginResponse")
	proto.RegisterType((*AccountLogoutRequest)(nil), "agency.AccountLogoutRequest")
	proto.RegisterType((*AccountLogoutResponse)(nil), "agency.AccountLogoutResponse")
	proto.RegisterType((*CustomerLookupRequest)(nil), "agency.CustomerLookupRequest")
	proto.RegisterType((*CustomerLookupResponse)(nil), "agency.CustomerLookupResponse")
	proto.RegisterType((*CustomerActionRequest)(nil), "agency.CustomerActionRequest")
	proto.RegisterType((*CustomerActionOrder)(nil), "agency.CustomerActionOrder")
	proto.RegisterType((*CustomerActionResponse)(nil), "agency.CustomerActionResponse")
	proto.RegisterType((*ReceiveFromSupplierRequest)(nil), "agency.ReceiveFromSupplierRequest")
	proto.RegisterType((*ReceiveFromSupplierResponse)(nil), "agency.ReceiveFromSupplierResponse")
	proto.RegisterType((*TransferToSupplierRequest)(nil), "agency.TransferToSupplierRequest")
	proto.RegisterType((*TransferToSupplierResponse)(nil), "agency.TransferToSupplierResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for BlueAgency service

type BlueAgencyClient interface {
	VersionInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VersionInfoResponse, error)
	AccountLogin(ctx context.Context, in *AccountLoginRequest, opts ...grpc.CallOption) (*AccountLoginResponse, error)
	AccountLogout(ctx context.Context, in *AccountLogoutRequest, opts ...grpc.CallOption) (*AccountLogoutResponse, error)
	CustomerLookup(ctx context.Context, in *CustomerLookupRequest, opts ...grpc.CallOption) (*CustomerLookupResponse, error)
	CustomerAction(ctx context.Context, in *CustomerActionRequest, opts ...grpc.CallOption) (*CustomerActionResponse, error)
	ReceiveFromSupplier(ctx context.Context, in *ReceiveFromSupplierRequest, opts ...grpc.CallOption) (*ReceiveFromSupplierResponse, error)
	TransferToSupplier(ctx context.Context, in *TransferToSupplierRequest, opts ...grpc.CallOption) (*TransferToSupplierResponse, error)
}

type blueAgencyClient struct {
	cc *grpc.ClientConn
}

func NewBlueAgencyClient(cc *grpc.ClientConn) BlueAgencyClient {
	return &blueAgencyClient{cc}
}

func (c *blueAgencyClient) VersionInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VersionInfoResponse, error) {
	out := new(VersionInfoResponse)
	err := grpc.Invoke(ctx, "/agency.BlueAgency/VersionInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blueAgencyClient) AccountLogin(ctx context.Context, in *AccountLoginRequest, opts ...grpc.CallOption) (*AccountLoginResponse, error) {
	out := new(AccountLoginResponse)
	err := grpc.Invoke(ctx, "/agency.BlueAgency/AccountLogin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blueAgencyClient) AccountLogout(ctx context.Context, in *AccountLogoutRequest, opts ...grpc.CallOption) (*AccountLogoutResponse, error) {
	out := new(AccountLogoutResponse)
	err := grpc.Invoke(ctx, "/agency.BlueAgency/AccountLogout", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blueAgencyClient) CustomerLookup(ctx context.Context, in *CustomerLookupRequest, opts ...grpc.CallOption) (*CustomerLookupResponse, error) {
	out := new(CustomerLookupResponse)
	err := grpc.Invoke(ctx, "/agency.BlueAgency/CustomerLookup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blueAgencyClient) CustomerAction(ctx context.Context, in *CustomerActionRequest, opts ...grpc.CallOption) (*CustomerActionResponse, error) {
	out := new(CustomerActionResponse)
	err := grpc.Invoke(ctx, "/agency.BlueAgency/CustomerAction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blueAgencyClient) ReceiveFromSupplier(ctx context.Context, in *ReceiveFromSupplierRequest, opts ...grpc.CallOption) (*ReceiveFromSupplierResponse, error) {
	out := new(ReceiveFromSupplierResponse)
	err := grpc.Invoke(ctx, "/agency.BlueAgency/ReceiveFromSupplier", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blueAgencyClient) TransferToSupplier(ctx context.Context, in *TransferToSupplierRequest, opts ...grpc.CallOption) (*TransferToSupplierResponse, error) {
	out := new(TransferToSupplierResponse)
	err := grpc.Invoke(ctx, "/agency.BlueAgency/TransferToSupplier", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BlueAgency service

type BlueAgencyServer interface {
	VersionInfo(context.Context, *Empty) (*VersionInfoResponse, error)
	AccountLogin(context.Context, *AccountLoginRequest) (*AccountLoginResponse, error)
	AccountLogout(context.Context, *AccountLogoutRequest) (*AccountLogoutResponse, error)
	CustomerLookup(context.Context, *CustomerLookupRequest) (*CustomerLookupResponse, error)
	CustomerAction(context.Context, *CustomerActionRequest) (*CustomerActionResponse, error)
	ReceiveFromSupplier(context.Context, *ReceiveFromSupplierRequest) (*ReceiveFromSupplierResponse, error)
	TransferToSupplier(context.Context, *TransferToSupplierRequest) (*TransferToSupplierResponse, error)
}

func RegisterBlueAgencyServer(s *grpc.Server, srv BlueAgencyServer) {
	s.RegisterService(&_BlueAgency_serviceDesc, srv)
}

func _BlueAgency_VersionInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlueAgencyServer).VersionInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agency.BlueAgency/VersionInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlueAgencyServer).VersionInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlueAgency_AccountLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlueAgencyServer).AccountLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agency.BlueAgency/AccountLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlueAgencyServer).AccountLogin(ctx, req.(*AccountLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlueAgency_AccountLogout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountLogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlueAgencyServer).AccountLogout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agency.BlueAgency/AccountLogout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlueAgencyServer).AccountLogout(ctx, req.(*AccountLogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlueAgency_CustomerLookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerLookupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlueAgencyServer).CustomerLookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agency.BlueAgency/CustomerLookup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlueAgencyServer).CustomerLookup(ctx, req.(*CustomerLookupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlueAgency_CustomerAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlueAgencyServer).CustomerAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agency.BlueAgency/CustomerAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlueAgencyServer).CustomerAction(ctx, req.(*CustomerActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlueAgency_ReceiveFromSupplier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveFromSupplierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlueAgencyServer).ReceiveFromSupplier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agency.BlueAgency/ReceiveFromSupplier",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlueAgencyServer).ReceiveFromSupplier(ctx, req.(*ReceiveFromSupplierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlueAgency_TransferToSupplier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferToSupplierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlueAgencyServer).TransferToSupplier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agency.BlueAgency/TransferToSupplier",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlueAgencyServer).TransferToSupplier(ctx, req.(*TransferToSupplierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlueAgency_serviceDesc = grpc.ServiceDesc{
	ServiceName: "agency.BlueAgency",
	HandlerType: (*BlueAgencyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VersionInfo",
			Handler:    _BlueAgency_VersionInfo_Handler,
		},
		{
			MethodName: "AccountLogin",
			Handler:    _BlueAgency_AccountLogin_Handler,
		},
		{
			MethodName: "AccountLogout",
			Handler:    _BlueAgency_AccountLogout_Handler,
		},
		{
			MethodName: "CustomerLookup",
			Handler:    _BlueAgency_CustomerLookup_Handler,
		},
		{
			MethodName: "CustomerAction",
			Handler:    _BlueAgency_CustomerAction_Handler,
		},
		{
			MethodName: "ReceiveFromSupplier",
			Handler:    _BlueAgency_ReceiveFromSupplier_Handler,
		},
		{
			MethodName: "TransferToSupplier",
			Handler:    _BlueAgency_TransferToSupplier_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agency/agency.proto",
}

func init() { proto.RegisterFile("agency/agency.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 906 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x06, 0xa5, 0x46, 0x92, 0x87, 0x76, 0xe2, 0xae, 0x62, 0x9b, 0xa6, 0xa5, 0xc0, 0xde, 0x34,
	0x80, 0x9b, 0xd4, 0x62, 0xaa, 0x5c, 0x0a, 0x5f, 0x0a, 0xa7, 0x70, 0x0b, 0x17, 0x01, 0x52, 0x50,
	0x6e, 0x0f, 0xbd, 0x18, 0x34, 0xb9, 0x62, 0x08, 0x93, 0x5c, 0x76, 0x77, 0xa9, 0xc2, 0xc7, 0xfe,
	0xbc, 0x41, 0x6f, 0x7d, 0x84, 0xbe, 0x45, 0x9f, 0xa1, 0x97, 0x3e, 0x40, 0x1f, 0xa4, 0xe0, 0xfe,
	0x48, 0xa2, 0x44, 0x1b, 0x3e, 0x49, 0x33, 0xf3, 0xcd, 0x7c, 0xdf, 0xec, 0xce, 0x0e, 0x08, 0xfd,
	0x20, 0x26, 0x79, 0x78, 0xeb, 0xa9, 0x9f, 0x51, 0xc1, 0xa8, 0xa0, 0xa8, 0xa3, 0x2c, 0x17, 0xe9,
	0x60, 0x46, 0x23, 0x92, 0xaa, 0x98, 0x3b, 0x88, 0x29, 0x8d, 0x53, 0xe2, 0x05, 0x45, 0xe2, 0x05,
	0x79, 0x4e, 0x45, 0x20, 0x12, 0x9a, 0x73, 0x1d, 0xdd, 0xd3, 0x51, 0x56, 0x84, 0x1e, 0x17, 0x81,
	0x28, 0x75, 0x00, 0x77, 0xe1, 0xd1, 0x79, 0x56, 0x88, 0x5b, 0x9c, 0x42, 0xff, 0x07, 0xc2, 0x78,
	0x42, 0xf3, 0x8b, 0x7c, 0x4a, 0x7d, 0xc2, 0x0b, 0x9a, 0x73, 0x82, 0x1c, 0xe8, 0x72, 0xc2, 0x66,
	0x49, 0x48, 0x1c, 0xeb, 0xd0, 0x3a, 0xde, 0xf0, 0x8d, 0x59, 0x45, 0x66, 0x2a, 0xc1, 0x69, 0xa9,
	0x88, 0x36, 0xd1, 0x11, 0x6c, 0x96, 0x45, 0x14, 0x08, 0x12, 0x5d, 0x89, 0x24, 0x23, 0x4e, 0xfb,
	0xd0, 0x3a, 0x6e, 0xfb, 0xb6, 0xf6, 0x5d, 0x26, 0x19, 0xc1, 0xdf, 0x40, 0xff, 0x2c, 0x0c, 0x69,
	0x99, 0x8b, 0x77, 0x34, 0x4e, 0x72, 0x9f, 0xfc, 0x54, 0x12, 0x2e, 0xd0, 0x53, 0x78, 0x54, 0x7c,
	0xa0, 0xb9, 0xe1, 0x52, 0x06, 0x72, 0xa1, 0x57, 0x04, 0x9c, 0xff, 0x4c, 0x59, 0xa4, 0xa9, 0xe6,
	0x36, 0xfe, 0xdd, 0x82, 0xa7, 0xf5, 0x4a, 0x5a, 0xf8, 0x1e, 0x74, 0x4b, 0x4e, 0xd8, 0x55, 0x12,
	0xe9, 0x62, 0x9d, 0xca, 0xbc, 0x88, 0x2a, 0x75, 0x41, 0x18, 0x12, 0xce, 0xaf, 0x04, 0xbd, 0x21,
	0x46, 0xbc, 0xad, 0x7c, 0x97, 0x95, 0x0b, 0xbd, 0x86, 0x0d, 0x95, 0x9b, 0x4f, 0xa9, 0x54, 0x6f,
	0x8f, 0xfb, 0x23, 0x7d, 0x13, 0x67, 0xf2, 0x67, 0x22, 0x82, 0xe9, 0xd4, 0xef, 0xc9, 0x92, 0xf9,
	0x94, 0xe2, 0xdd, 0x65, 0x15, 0xb4, 0x14, 0xba, 0x21, 0xbc, 0x07, 0x3b, 0x2b, 0x7e, 0x25, 0x0f,
	0x9f, 0xc0, 0xce, 0x57, 0x25, 0x17, 0x34, 0x23, 0xec, 0x1d, 0xa5, 0x37, 0x65, 0x71, 0xef, 0x11,
	0xe0, 0xbf, 0x2d, 0xd8, 0x5d, 0xc5, 0xeb, 0x46, 0x5f, 0xc0, 0xe3, 0x50, 0x47, 0x74, 0x47, 0x2a,
	0x73, 0xcb, 0x78, 0x55, 0x4f, 0x9f, 0x41, 0xcf, 0x38, 0x64, 0xcb, 0xf6, 0x78, 0xdb, 0xb4, 0x64,
	0x0a, 0xfb, 0x73, 0x04, 0x7a, 0x05, 0x3d, 0x7d, 0xcf, 0xdc, 0x69, 0x1f, 0xb6, 0x8f, 0xed, 0xf1,
	0x13, 0x83, 0x9e, 0x28, 0xbf, 0x3f, 0x07, 0xa0, 0x17, 0xd0, 0xa1, 0x2c, 0x22, 0x8c, 0x3b, 0x1f,
	0x49, 0xe8, 0x96, 0x81, 0xbe, 0xaf, 0xbc, 0xbe, 0x0e, 0xe2, 0x3f, 0xad, 0x45, 0xcf, 0x67, 0x61,
	0x35, 0x9d, 0xa6, 0xe7, 0x07, 0xb6, 0xb0, 0x0c, 0x53, 0x67, 0xd4, 0xaa, 0xc3, 0xbe, 0x93, 0xe3,
	0xf2, 0x66, 0x2e, 0x47, 0x29, 0x3f, 0x58, 0xed, 0x53, 0x91, 0xd7, 0xc5, 0xbd, 0x87, 0x7e, 0x43,
	0x18, 0xed, 0x43, 0x4f, 0x02, 0x16, 0x63, 0xd4, 0x95, 0xf6, 0x45, 0x84, 0x86, 0x00, 0xfa, 0x04,
	0xaa, 0xa0, 0x52, 0xb2, 0xa1, 0x3d, 0x17, 0x11, 0xfe, 0xb7, 0xb5, 0xb8, 0x31, 0xd3, 0xad, 0xbe,
	0xb1, 0xef, 0x61, 0x4b, 0x15, 0xe5, 0xa5, 0x1c, 0x3a, 0xc7, 0x92, 0x3a, 0x5f, 0x37, 0xeb, 0x34,
	0x69, 0xea, 0x34, 0x27, 0x2a, 0xe5, 0x3c, 0x17, 0xec, 0xd6, 0xdf, 0xa4, 0x4b, 0x2e, 0xe4, 0x83,
	0xb2, 0xaf, 0x08, 0x63, 0x94, 0x71, 0xa7, 0x25, 0xab, 0x7a, 0x0f, 0xa9, 0x7a, 0x2e, 0x33, 0x54,
	0x51, 0x9b, 0x2e, 0x3c, 0xee, 0x97, 0xf0, 0xf1, 0x1a, 0x2d, 0xda, 0x86, 0xf6, 0x0d, 0xb9, 0xd5,
	0xe7, 0x51, 0xfd, 0xad, 0x86, 0x76, 0x16, 0xa4, 0xa5, 0xb9, 0x10, 0x65, 0x9c, 0xb6, 0xbe, 0xb0,
	0x5c, 0x1f, 0xb6, 0x57, 0x19, 0x1a, 0xf2, 0x8f, 0x97, 0xf3, 0xed, 0x31, 0x1a, 0xa9, 0x75, 0x35,
	0x62, 0x45, 0x38, 0x9a, 0xc8, 0x75, 0xb5, 0x54, 0x13, 0x0f, 0xc0, 0xf5, 0x49, 0x48, 0x92, 0x19,
	0xf9, 0x9a, 0xd1, 0x6c, 0x52, 0x16, 0x45, 0x9a, 0x10, 0x66, 0x9e, 0xdc, 0x10, 0x0e, 0x1a, 0xa3,
	0xfa, 0xe1, 0x1d, 0xc0, 0xfe, 0x25, 0x0b, 0x72, 0x3e, 0xad, 0xa6, 0x6a, 0x35, 0x77, 0x00, 0x6e,
	0x53, 0x50, 0xa5, 0x8e, 0xff, 0xea, 0x00, 0xbc, 0x4d, 0x4b, 0xa2, 0x56, 0x00, 0xfa, 0x16, 0xec,
	0xa5, 0x8d, 0x89, 0xe6, 0x53, 0x2f, 0xf7, 0xa9, 0x3b, 0x9f, 0xba, 0x86, 0xad, 0x8a, 0x9f, 0xfc,
	0xfa, 0xcf, 0x7f, 0x7f, 0xb4, 0x36, 0x50, 0x57, 0xae, 0xeb, 0xd9, 0xe7, 0xe8, 0x06, 0x36, 0x97,
	0xb7, 0x18, 0x9a, 0x67, 0x37, 0x6c, 0x49, 0x77, 0xd0, 0x1c, 0xd4, 0xb5, 0x0f, 0x65, 0x6d, 0x17,
	0xef, 0xe8, 0xda, 0x5e, 0xa0, 0x50, 0x5e, 0x5a, 0xc1, 0x4e, 0xad, 0x97, 0x88, 0xc2, 0x56, 0x6d,
	0x29, 0xa1, 0x86, 0x82, 0x8b, 0x1d, 0xe6, 0x0e, 0xef, 0x88, 0x6a, 0xbe, 0x23, 0xc9, 0x77, 0x80,
	0x77, 0x1b, 0xf8, 0x68, 0x29, 0x2a, 0x42, 0x0e, 0x8f, 0xeb, 0xcb, 0x0b, 0x0d, 0x57, 0xa7, 0xb2,
	0xb6, 0x04, 0xdd, 0x67, 0x77, 0x85, 0x35, 0x27, 0x96, 0x9c, 0x03, 0xbc, 0x67, 0x38, 0xcd, 0x06,
	0xf0, 0x52, 0x09, 0x5c, 0x21, 0x55, 0x23, 0xbf, 0x4e, 0x5a, 0xdb, 0x42, 0xeb, 0xa4, 0xf5, 0x97,
	0x72, 0x0f, 0x69, 0x20, 0x81, 0x15, 0xe9, 0x6f, 0x16, 0xf4, 0x1b, 0xa6, 0x0f, 0x61, 0x53, 0xfb,
	0xee, 0xc1, 0x75, 0x9f, 0xdf, 0x8b, 0xd1, 0x22, 0x9e, 0x4b, 0x11, 0x43, 0xec, 0x18, 0x11, 0x5c,
	0x23, 0x3c, 0xa6, 0xb2, 0x2a, 0x15, 0xbf, 0x58, 0x80, 0xd6, 0xe7, 0x18, 0x1d, 0x19, 0x82, 0x3b,
	0x1f, 0x80, 0x8b, 0xef, 0x83, 0x68, 0x09, 0x9f, 0x48, 0x09, 0xcf, 0xf0, 0xfe, 0x9a, 0x04, 0xa1,
	0x93, 0x4e, 0xad, 0x97, 0x6f, 0x5f, 0xfd, 0xf8, 0x69, 0x9c, 0x88, 0x0f, 0xe5, 0xf5, 0x28, 0xa4,
	0x99, 0x97, 0xc7, 0x27, 0xb3, 0xd2, 0x8b, 0xe9, 0x49, 0xcc, 0x8a, 0xf0, 0x84, 0x07, 0x59, 0x91,
	0x12, 0xaf, 0xb8, 0xd6, 0x9f, 0x37, 0xd7, 0x1d, 0xf9, 0x31, 0xf2, 0xe6, 0xff, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xb7, 0x01, 0x75, 0x5c, 0xf6, 0x08, 0x00, 0x00,
}
