// Generated by idconsts_gen. DO NOT EDIT.
package model

const InfixAgencyStaff = Infix(16470)
const InfixBlueStaff = Infix(16566)
const InfixService = Infix(49358)
const InfixServiceProvider = Infix(32973)
const InfixOrder = Infix(176)
const InfixOrderTransaction = Infix(32774)
const InfixMoneyTransaction = Infix(32934)

var str2infix = map[string]Infix{
	"AS": InfixAgencyStaff,
	"PS": InfixBlueStaff,
	"SV": InfixService,
	"SP": InfixServiceProvider,
	"P0": InfixOrder,
	"0T": InfixOrderTransaction,
	"MT": InfixMoneyTransaction,
}
var infix2str = map[Infix]string{
	InfixAgencyStaff:      "AS",
	InfixBlueStaff:        "PS",
	InfixService:          "SV",
	InfixServiceProvider:  "SP",
	InfixOrder:            "P0",
	InfixOrderTransaction: "0T",
	InfixMoneyTransaction: "MT",
}
